### ISSUE TITLE
[PE-D] Duration parameter in schedule workspace only accepts integers

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113T-T10-2/tp#165] opened 2021-10-30 17:30 UTC
If user inputs "0.5" as the duration, which is a positive number as recommended by UG, the program returns error message: Invalid duration format.

Such durations as floating-point values to indicate 30min or 45min durations are legitimate user behavior which the program fails to accept.

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: KVignesh122/ped#3

**Comment by kelvneo** [comment] 2021-10-30 17:35
Duplicate of #162

**Closed by kelvneo** 2021-10-30 17:35 UTC
